// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libcoinor_path=file('join',['.','libcoinor.so']);
addinter(libcoinor_path,'libcoinor');
