// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libcoinmp_path=file('join',['.','libcoinmp.so']);
addinter(libcoinmp_path,'libcoinmp');
